### PR TITLE
Add Dockerfile and update to Opencv 4, among other improvements.

### PR DESCRIPTION
**Pull request by andyblarblar**
This PR begins to modernize the repo with some non-breaking but very helpful improvements. Please check 'future considerations' on the bottom for more info on what still needs to be done.

Changelog 📝
=========
[+] - Add docker dev container. **Password in container is 1234**
[+] - Move packages into `src` to allow for [use of catkin tools.](https://catkin-tools.readthedocs.io/en/latest/)
~~[+] - Add isc_joy as a git submodule as it is a related dependancy.~~
[\~] - Migrate opencv 3 code to opencv 4, and change cmake dependacy.
~~[+] - Add other dependancies (serial, serial_util ect.) into `src/include` when the dockerfile is run. These are gitignored.~~
[+] - All git dependacies can be installed with vcstool. This is automaticly done in the docker container.

Details 🔬
======
## Dockerfile

The docker dev container provides a full ubuntu based ROS Noetic develupment with all of our build deps installed. It can be run on any OS, and is best used with vscode.

To use the dev container:
- Install docker desktop on macos or windows, or docker and docker compose on linux.
- If on linux, add your user to the docker group. This may be needed on macos too, but I dont have a macbook to test it on.
- Install vscode, and add the 'C++ extention pack' extention. This will add the remote tools needed, as well as all the C++ tools needed.
- Now just reboot, and clone this PR. You should see a 'open in container' toast in the bottom right. Click this.
- If that didn't show up, click the remote vscode icon in the bottom left corner, and then 'reopen in container'.
- The Dockerfile should now be built. This only needs to be done once, but can take a bit, and about 3Gb of storage.
- Once done, you should be remoted into the docker container! Run `catkin build` to attempt to build the repo! ~~This should just work, but may need you to `source` the `/devel/setup.bash` file on first use.~~ To hop between the container and local, use the bottom left green button. This is your normal volume mounted, so try not to nuke your drive in the terminal, as it _Will_ change any file in the `workspaces/Ohm` directory. ~~I would advise using git outside of the container, as the git files will be owned by the container, causing weird nonsense. I use GitKraken for this purpase.~~ If you want to change the Dockerfile, edit it in `.devcontainers` and rebuild it. You'll prob need to install other docker dev features to do this, but I'm sure you can figure it out ;).

Do note the .vscode folder in the project root. _This is required_, and is manually configured. Without it, vscode will run out of file handles and fail to watch files. It also manually configures the cpp include paths to work with ROS.

## catkin_tools

catkin tools is a python script wrapping CATKIN_MAKE that massivly improves upon its usablity. From what I can tell, this is the current ROS1 community standard build system. It essentally builds all packages (or just one if you want) in parrellel and independantly to speed things up. I have this installed in the docker container.

## Opencv 4

This is a simple migration, only took like 4 changed constants. There doesnt seem to be any breaking changes, but we should really test before using this in prod. <sub>(Frankly, we should unit test more in general, but thats for another PR)</sub>

Future considerations 🔮
===============
- ~~The Dockerfile uses `root`. This should be swapped to a standard user. Currently this change is blocked by some issues on vscodes side.~~ Done in this PR.
- All Cmake and C++ versions can be bumped to `3.16` and `C++14` respectivly. This is a non-breaking change, and will give us a nice bump in usablity. 
- ~~Gazebo has a docker container. We should attempt to automate its creation for use as a dev container similar to this one.~~ This container can be run with the osrf/rocker tool to remote into Gazebo.
- When migrating to ROS2, This dockerfile can be swapped with one based on an `osrf/ros2` container to automaticly convert to an ROS2 enviorment.
- We should really write some unit tests and integration tests that wire into ROS's test system.
- Document!

### CODE REVIEW

**Comment by davidcutting** [comment]
Hey Andy, thanks for the clean PR.

What are your thoughts on using wstool or vcstool instead of git submodules for pulling the ros dependencies that are not apt packages, such as ISC repos?

**Comment by andyblarblar** [comment]
I havent seen vsctool before, but it seems like it may be cleaner for handling deps. I think it'll for sure be cleaner for pulling non-isc repos, as right now im cloning and then copying which is a bit of a mess. I'll have to see how tooling reacts to nested git repos that arn't submodules, as I want to make sure we can easily use, for example, a branch of isc_joy maintained between the two teams. Either way, ill look into using vcstool when I get the time.

**Comment by andyblarblar** [comment]
@dcutting133 This PR should be all ready to merge from my end. It now uses vcstool in lew of modules, runs as non-root in the docker container, and no longer needs a few cloned directories. I've attempted to document the container well, so it should be maintainable even if there isn't another docker user in the future. Just let me know if you need anything else :)

**Comment by andyblarblar** [comment]
Just tested, using [rocker](https://github.com/osrf/rocker) you can use any GUI application (including gazebo, which is already installed) through this docker image.

My rocker cmd on Intel GPU looks like this for reference: `sudo rocker --x11 --devices '/dev/dri/card0' -- ohm:latest gazebo`

**Comment by andyblarblar** [comment]
Actually, I think I'm going to attempt to modify the docker container to expose an SSH port and clone the repo internally. This would mean any IDE (vscode and Clion at least) with SSH support could just remote into the container and use the env. This would be more flexable, albeat more verbose. Intristingly, this image could actually be used in the production Ohm if we wanted to, allowing us to share our prod and dev enviorments. Just a thought. Converting to draft until done.

TODO:
-------

- [ ] Expose SSH
- [ ] Remove Vscode spesific code
- [ ] Clone Repo into container
- [x] Add proper build and caching steps

**Comment by andyblarblar** [comment]
After a 3 day battle with docker, I must admit defeat. Reopening this PR as is, as it is by far the most stable I've been able to get this setup. The PR as is may only work on Vscode, but it works pretty flawlessly.

**Comment by girvenavery2022** [comment]
That's okay! I am a bit busy right now, but I'll review it this week!

**Comment by andyblarblar** [comment]
I should mention that the Dockerfile will need to be updated whenever we gain a system dependancy, or it will no longer be able to compile (This is because docker containers reset everytime you use them, so you can't just apt install in the container). This will be neccicary when installing the ros gazebo plugins for example.

**Comment by andyblarblar** [comment]
Migrating the workspace configuration portion of this PR into its own repo [here](https://github.com/andyblarblar/ohm-dev-env), and opening the code changes in #8. Closing this PR.

**Pull request closed without merging**
